<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit01648e50df43d746557bb6e6e7a02dfa
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        'a4a119a56e50fbb293281d9a48007e0e' => __DIR__ . '/..' . '/symfony/polyfill-php80/bootstrap.php',
        '60799491728b879e74601d83e38b2cad' => __DIR__ . '/..' . '/illuminate/collections/helpers.php',
        'a1105708a18b76903365ca1c4aa61b02' => __DIR__ . '/..' . '/symfony/translation/Resources/functions.php',
        '72579e7bd17821bb1321b87411366eae' => __DIR__ . '/..' . '/illuminate/support/helpers.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        '8825ede83f2f289127722d4e842cf7e8' => __DIR__ . '/..' . '/symfony/polyfill-intl-grapheme/bootstrap.php',
        'e69f7f6ee287b969198c3c9d6777bd38' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/bootstrap.php',
        '0d59ee240a4cd96ddbb4ff164fccea4d' => __DIR__ . '/..' . '/symfony/polyfill-php73/bootstrap.php',
        'b6b991a57620e2fb6b2f66f03fe9ddc2' => __DIR__ . '/..' . '/symfony/string/Resources/functions.php',
        '72142d7b40a3a0b14e91825290b5ad82' => __DIR__ . '/..' . '/cakephp/core/functions.php',
        '948ad5488880985ff1c06721a4e447fe' => __DIR__ . '/..' . '/cakephp/utility/bootstrap.php',
        '538ca81a9a966a6716601ecf48f4eaef' => __DIR__ . '/..' . '/opis/closure/functions.php',
        'e39a8b23c42d4e1452234d762b03835a' => __DIR__ . '/..' . '/ramsey/uuid/src/functions.php',
        'ef65a1626449d89d0811cf9befce46f0' => __DIR__ . '/..' . '/illuminate/events/functions.php',
        '9e4824c5afbdc1482b6025ce3d4dfde8' => __DIR__ . '/..' . '/league/csv/src/functions_include.php',
    );

    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'BoldMinded\\DataGrab\\FieldTypes\\' => 31,
            'BoldMinded\\DataGrab\\Dependency\\voku\\' => 36,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Php80\\' => 54,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Php73\\' => 54,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Mbstring\\' => 57,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 64,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Intl\\Grapheme\\' => 62,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Ctype\\' => 54,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Contracts\\Translation\\' => 61,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Contracts\\Service\\' => 57,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\Translation\\' => 61,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\String\\' => 56,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\Process\\' => 57,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\Finder\\' => 56,
            'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\Console\\' => 57,
            'BoldMinded\\DataGrab\\Dependency\\Ramsey\\Uuid\\' => 43,
            'BoldMinded\\DataGrab\\Dependency\\Ramsey\\Collection\\' => 49,
            'BoldMinded\\DataGrab\\Dependency\\Psr\\SimpleCache\\' => 47,
            'BoldMinded\\DataGrab\\Dependency\\Psr\\Container\\' => 45,
            'BoldMinded\\DataGrab\\Dependency\\Opis\\Closure\\' => 44,
            'BoldMinded\\DataGrab\\Dependency\\Litzinger\\Basee\\' => 47,
            'BoldMinded\\DataGrab\\Dependency\\League\\Csv\\' => 42,
            'BoldMinded\\DataGrab\\Dependency\\League\\Container\\' => 48,
            'BoldMinded\\DataGrab\\Dependency\\Laravel\\SerializableClosure\\' => 59,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Support\\' => 50,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Redis\\' => 48,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Queue\\' => 48,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Pipeline\\' => 51,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Filesystem\\' => 53,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Events\\' => 49,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Database\\' => 51,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Contracts\\' => 52,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Container\\' => 52,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Console\\' => 50,
            'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Bus\\' => 46,
            'BoldMinded\\DataGrab\\Dependency\\Doctrine\\Inflector\\' => 50,
            'BoldMinded\\DataGrab\\Dependency\\Carbon\\' => 38,
            'BoldMinded\\DataGrab\\Dependency\\Cake\\Utility\\' => 44,
            'BoldMinded\\DataGrab\\Dependency\\Cake\\Core\\' => 41,
            'BoldMinded\\DataGrab\\Dependency\\Brick\\Math\\' => 42,
            'BoldMinded\\DataGrab\\Dependency\\Bamarni\\Composer\\Bin\\' => 52,
            'BoldMinded\\DataGrab\\DataTypes\\' => 30,
            'BoldMinded\\DataGrab\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'BoldMinded\\DataGrab\\FieldTypes\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/addons/datagrab/fieldtypes',
        ),
        'BoldMinded\\DataGrab\\Dependency\\voku\\' => 
        array (
            0 => __DIR__ . '/..' . '/voku/portable-ascii/src/voku',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Php80\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php80',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Php73\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php73',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Intl\\Grapheme\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-grapheme',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Contracts\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation-contracts',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Contracts\\Service\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/service-contracts',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\String\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/string',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Ramsey\\Uuid\\' => 
        array (
            0 => __DIR__ . '/..' . '/ramsey/uuid/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Ramsey\\Collection\\' => 
        array (
            0 => __DIR__ . '/..' . '/ramsey/collection/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Opis\\Closure\\' => 
        array (
            0 => __DIR__ . '/..' . '/opis/closure/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Litzinger\\Basee\\' => 
        array (
            0 => __DIR__ . '/..' . '/litzinger/basee/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\League\\Csv\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/csv/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\League\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/container/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Laravel\\SerializableClosure\\' => 
        array (
            0 => __DIR__ . '/..' . '/laravel/serializable-closure/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Support\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/collections',
            1 => __DIR__ . '/..' . '/illuminate/macroable',
            2 => __DIR__ . '/..' . '/illuminate/support',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Redis\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/redis',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Queue\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/queue',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Pipeline\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/pipeline',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/filesystem',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Events\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/events',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Database\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/database',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Contracts\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/contracts',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/container',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/console',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Illuminate\\Bus\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/bus',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Doctrine\\Inflector\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/inflector/lib/Doctrine/Inflector',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Carbon\\' => 
        array (
            0 => __DIR__ . '/..' . '/nesbot/carbon/src/Carbon',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Cake\\Utility\\' => 
        array (
            0 => __DIR__ . '/..' . '/cakephp/utility',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Cake\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/cakephp/core',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Brick\\Math\\' => 
        array (
            0 => __DIR__ . '/..' . '/brick/math/src',
        ),
        'BoldMinded\\DataGrab\\Dependency\\Bamarni\\Composer\\Bin\\' => 
        array (
            0 => __DIR__ . '/..' . '/bamarni/composer-bin-plugin/src',
        ),
        'BoldMinded\\DataGrab\\DataTypes\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/addons/datagrab/datatypes',
        ),
        'BoldMinded\\DataGrab\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/addons/datagrab',
        ),
    );

    public static $classMap = array (
        'BoldMinded\\DataGrab\\Dependency\\Attribute' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Attribute.php',
        'BoldMinded\\DataGrab\\Dependency\\JsonException' => __DIR__ . '/..' . '/symfony/polyfill-php73/Resources/stubs/JsonException.php',
        'BoldMinded\\DataGrab\\Dependency\\Normalizer' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
        'BoldMinded\\DataGrab\\Dependency\\PhpToken' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/PhpToken.php',
        'BoldMinded\\DataGrab\\Dependency\\Stringable' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Stringable.php',
        'BoldMinded\\DataGrab\\Dependency\\UnhandledMatchError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php',
        'BoldMinded\\DataGrab\\Dependency\\ValueError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/ValueError.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit01648e50df43d746557bb6e6e7a02dfa::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit01648e50df43d746557bb6e6e7a02dfa::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit01648e50df43d746557bb6e6e7a02dfa::$classMap;

        }, null, ClassLoader::class);
    }
}
